import java.util.ArrayList;
import java.io.BufferedReader;
import java.io.FileReader;
import java.io.BufferedWriter;
import java.io.FileWriter;
import java.math.BigDecimal;

/**
 * UserManager
 *
 * This class is the driver for all interactions with the User class.
 * It organizes all users in a list. These users are drawn through this class'
 * methods. This class also handles all creation, deletion, saving, and searching
 * of the user objects and files.
 *
 * @author David Goldfuss, L06
 * @version November 8th, 2025
 */

public class UserManager implements UserManagerInterface {
    private ArrayList<User> userList;  // This is the list to hold all the user objects
    private String userDataPath;  // The path to the file to get user data from
    private Object userFileLock = new Object();  // The sync lock for the user file
    private Object userListLock = new Object(); // The sync lock for the user list
    /**
     * This is the constructor for the class. It creates a new instance of the class and
     * sets the usetList to a empty ArrayList of users.
     *
     * @param userDataPath This is the path to grab the user data from
     */
    public UserManager(String userDataPath) {
        this.userDataPath = userDataPath;
        this.userList = new ArrayList<User>();
    }

    /**
     * This method reads in all of the users from the usersData.txt file. It parses that data
     * into different variables of various types, and then constructs a new user object with that.
     * The method then adds each of those user objects into the userList.
     */
    public void readUsers() {
        ArrayList<String> userLines = new ArrayList<String>();  // The list of each line in the file
        synchronized (userFileLock) {
            try (BufferedReader userReader = new BufferedReader(new FileReader(userDataPath))) {
                String line = userReader.readLine();  // The current line being read
                while (line != null) {
                    userLines.add(line);
                    line = userReader.readLine();
                }
            } catch (Exception e) {
                System.out.println("Failure reading user file");
            }
        }
        synchronized (userListLock) {
            userList = parseUserData(userLines);
        }
    }  // End readUsers

    /**
     * This method returns the userList ArrayList.
     *
     * @return The ArrayList that contains all of the User objects
     */
    public ArrayList<User> getUserList() {
        synchronized (userListLock) {
            return userList;
        }
    }

    /**
     * This method takes an ArrayList of String each containing user data
     * and parses it out to an ArrayList of user objects.
     * It uses the formatting of those String in order to find the specific variable types
     * of each User object before making it.
     *
     * @param userLines The userLines parameter is an ArrayList of each line of the
     * text file that needs to be converted into a User object.
     * @return An ArrayList of Users that is generated by parsing through each line
     */
    private ArrayList<User> parseUserData(ArrayList<String> userLines) {
        ArrayList<User> usersFromData = new ArrayList<User>();  // The users to be returned by the method
        for (String userStr : userLines) {
            String[] params = userStr.split(",");  // The array of each parameter used to make the User object
            String userName;  // The username of the User
            String password;  // The password of the User
            double balance;  // The balance of the User
            boolean admin;
            ArrayList<Seat> seatList = new ArrayList<Seat>();  // The list of all of the seats the user owns

            // This makes an atempt to set all the values
            // it is in a try-catch in an attempt to catch invalid vaues
            try {
                userName = params[0];
                password = params[1];
                balance = Double.parseDouble(params[2]);
                admin = params[3].equals("true");

                // If the seatList uis not empty
                if (params.length > 4) {
                    seatList = parseSeatList(params[4]);
                }
                User tempUser = new User(userName, admin, password, balance, seatList, this);
                usersFromData.add(tempUser);  // The user being made
            } catch (Exception e) {
                System.out.println("Corrupted data found in user.txt, skipping this user");
            }  // End try catch
        } // end for
        return usersFromData;
    }  // End parseUserData

    /**
     * This method takes in a string which is a list of seat id separated by a semi-colon and
     * then parses that out into an ArrayList of Seat object. It also throws and
     * Exception in the case that the string is not able to be parsed.
     *
     * @param seatString This is a string of all of the seats split by semi-colons
     * @return An ArrayList of individual Seat object
     */
    private ArrayList<Seat> parseSeatList(String seatString) throws Exception {
        ArrayList<Seat> seatList = new ArrayList<Seat>();  // The ArrayList of seat object to return
        if (seatString.contains(":")) {
            String[] stringArray = seatString.split(":");  // All of the individual seat IDs
            double[] seatsDouble = new double[stringArray.length];  // All of the IDs converted to doubles

            // Try to parse all of the Strings into doubles
            for (int i = 0; i < stringArray.length; i++) {
                try {
                    seatsDouble[i] = Double.parseDouble(stringArray[i]);
                } catch (Exception e) {
                    throw new Exception("Failure to parse seats, bad data");
                }
            }  // End for loop

            // Try to find all of the Seat objects by ID
            for (double seatsNum : seatsDouble) {
                try {
                    //seatList.add(new Seat(""+seatsNum)); 
                } catch (Exception e) {
                    throw new Exception("Failture to parse seats, seat id not found");
                }
            }  // End for loop
        }
        return seatList;
    }  // End parseSeatList

    /**
     * This method takes in a username and tries to find a matching user in the userList.
     *
     * @param username The username that is being searched for
     * @return A matching User object, will throw an exception if none is found
     */
    public User queryUsers(String username) {
        synchronized (userListLock) {
            for (int i = 0; i < userList.size(); i++) {
                if (userList.get(i).getUsername().equals(username)) {
                    return userList.get(i);
                }
            }
        }
        System.out.println("User does not exist, aborting query");
        return null;
    }

    /**
     * This method takes in a user and attemps to delete it both from the userList and the user file
     * @param user The user to be deleted
     */
    public void deleteUser(User user) {
        int removeId = -1;  // The index f the userList item to be removed

        synchronized (userListLock) {
            // Loops through all of the userList items and tries to find the matching index
            for (int i = 0; i < userList.size(); i++) {
                if (userList.get(i).getUsername().equals(user.getUsername())) {
                    removeId = i;
                }
            }

            // If a matching index was found remove it and rewrite the user file
            if (removeId != -1) {
                userList.remove(removeId);
                writeUsers();
            } else {
                System.out.println("Not deleting, could not find user");
            }
        }
    }

    /**
     * This method makes a new User object after ensuring that all of the parameters are valid. If the parameter are
     * not valid it returns a UserCreationException
     *
     * @param username The username of the user
     * @param name The name of the user
     * @param password The password of the user
     * @param balance The balance of the user
     * @param seatList The list of all of the seats the user owns
     * @return The user object that was created
     */

    public User makeUser(String username,
                         boolean admin,
                         String password,
                         double balance,
                         ArrayList<Seat> seatList
    ) throws UserCreationException {
        boolean uniqueID = true;  // If the username is not already taken

        synchronized (userListLock) {
            // Ensures that the username is not already taken by another user
            for (User user : userList) {
                if (user.getUsername().equals(username)) {
                    uniqueID = false;
                }
            }
        }

        // Ensures that all of the parameters are not null or empty
        if (password == null || password.equals("")) {
            throw new UserCreationException("Password is null or empty");
        }
        if (!uniqueID) {
            throw new UserCreationException("Username already taken");
        }
        if (username == null || username.equals("")) {
            throw new UserCreationException("Username is null or empty");
        }
        if (seatList == null) {
            throw new UserCreationException("Seat list is null");
        }

        User newUser = new User(username, admin, password, balance, seatList, this);  // The user that is being created
        synchronized (userListLock) {
            userList.add(newUser);
        }
        writeUsers();
        return newUser;
    }

    /**
     * This method checks to see if the inputed password
     * matches the user's password.
     *
     * @param user The user to check the password on
     * @param inPassword The password to check
     * @return A boolean that is if the passwords matched
     */
    public boolean validateUser(User user, String inPassword) {
        return user.getPassword().equals(inPassword);
    }
    /**
     * This method takes all of the User object in userList, turns them into formatted Strings containing all
     * of their data, and writes that data back to the usersData.txt file.
     */
    public void writeUsers() {
        ArrayList<String> userStrings = new ArrayList<String>();  // The list of all of the user strings to write

        synchronized (userListLock) {
            // Ensures that there are users in the list
            if (userList.size() > 0) {

                // Loops through every user and adds the parameters to the string
                for (User user : userList) {
                    String adminStr;
                    if (user.getAdmin()) {
                        adminStr = "true";
                    } else {
                        adminStr = "false";
                    }
                    String currentUserStr = "";  // The String for the current user
                    currentUserStr +=
                            user.getUsername() + ","
                                    + user.getPassword() + ","
                                    + user.getBalance() + ","
                                    + adminStr + ",";
                    String seatString = "";
                    for (Seat seat : user.getSeatList()) {
                        seatString += seat.getUsername() + ":";
                    }

                    // Ensures there are actually seats and then removes the last semi-colon
                    if (seatString.length() > 0) {
                        seatString = seatString.substring(0, seatString.length() - 1);
                    }
                    currentUserStr += seatString;
                    userStrings.add(currentUserStr);
                }

                // Compiles all of the user Strings into one long string split by \n's
                String allUsersString = "";  // The final String to write
                for (String usrStr : userStrings) {
                    allUsersString += usrStr + "\n";
                }

                allUsersString = allUsersString.substring(0, allUsersString.length() - 1);

                synchronized (userFileLock) {
                    // Writes the file back
                    try (BufferedWriter bfw = new BufferedWriter(new FileWriter(userDataPath))) {
                        bfw.write(allUsersString);
                    } catch (Exception e) {
                        System.out.println("Error writing user data");
                    }
                }
            } else {
                synchronized (userFileLock) {
                    try (BufferedWriter bfw = new BufferedWriter(new FileWriter(userDataPath))) {
                        bfw.write("");
                    } catch (Exception e) {
                        System.out.println("Error writing user data");
                    }
                }
            }
        }
    }
}
